# Generated by Django 4.2.10 on 2024-03-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_customerinvoice_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInvoice',
        ),
    ]
