# Generated by Django 4.2.10 on 2024-03-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_testmodel_remove_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_entry', to='adminapp.testmodel'),
        ),
    ]
