# Generated by Django 4.2.10 on 2024-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_testmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='Status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='UNPAID', max_length=10, null=True),
        ),
    ]
