# Generated by Django 4.2.10 on 2024-02-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
